3rd year/Web Interfaces for Data Management/Grupo-08-Projeto-Final-IWGD/reddit/reddit/reddit/urls.py
from django.urls import include, path, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('subreddit.urls')),
    path("accounts/", include("allauth.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.SERVE_MEDIA_FILES:
    urlpatterns += [
        re_path(r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'),
            serve,
            {'document_root': settings.MEDIA_ROOT}),
    ]

handler404 = 'subreddit.views.handler404'
handler500 = 'subreddit.views.handler500'

3rd year/Web Interfaces for Data Management/Grupo-08-Projeto-Final-IWGD/reddit/reddit/subreddit/urls.py
from django.urls import path
from . import views

app_name = 'subreddit'

urlpatterns = [
    path("", views.index, name='index'),
    path("registo/", views.registo, name='registo'),
    path("login/", views.login_view, name="login"),
    path('logout/', views.logoutview, name="logout"),
    path('about_me/',views.about_me, name="about_me"),
    path('perfil/', views.perfilview, name="perfil"),
    path("perfil/<str:username>/", views.perfilview, name="perfil"),
    path('perfil/seguidores/<str:username>/', views.list_followers, name='list_followers'),
    path('perfil/seguindo/<str:username>/', views.list_following, name='list_following'),
    path("chat_privado/<str:username>/", views.chat_privado, name="chat_privado"),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('listar_chats_privados/', views.listar_chats_privados, name='lista_chats_privados'),
    path("adicionar_amigo/<str:friend_username>/", views.follow_friend, name="seguir_amigo"),
    path("remover_amigo/<str:friend_username>/", views.unfollow_friend, name="unfollow_amigo"),
    path("<int:subreddit_id>/criar_post/", views.criar_post, name="criar_post"),
    path("criar_subreddit/", views.criar_subreddit, name="criar_subreddit"),
    path("<int:subreddit_id>/apagar_subreddit/", views.apagar_subreddit, name="apagar_subreddit"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/", views.detalhe_subreddit, name="detalhe_subreddit"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/filtrar_posts/", views.post_filter, name="filtrar_post"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/chat/", views.subreddit_chat, name="subreddit_chat"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/<str:sort_by>/", views.detalhe_subreddit, name="detalhe_subreddit"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/<str:sort_by>/filtrar_posts/", views.post_filter, name="filtrar_post"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/<int:post_id>/vote_post/", views.vote_post, name="vote_post"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/<int:post_id>/ver_detalhe_post/", views.detalhe_post, name="detalhe_post"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/<int:post_id>/ver_detalhe_post/filtrar_comentarios/", views.comment_filter, name="filtrar_comentario"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/<int:post_id>/delete_post/", views.delete_post, name="delete_post"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/<int:post_id>/criar_comentario/", views.criar_comentario, name="criar_comentario"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/<int:post_id>/editar_post/", views.edit_post, name="edit_post"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/<int:post_id>/editar_comentario/<int:comment_id>/",
         views.edit_comment, name="edit_comment"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/<int:post_id>/ver_detalhe_post/<int:comment_id>/", views.vote_comment, name="vote_comment"),
    path("<int:subreddit_id>/ver_detalhe_subreddit/<int:post_id>/delete_comment/<int:comment_id>/", views.delete_comment, name="delete_comment"),
    path("chat/", views.chat, name="chat"),


]

3rd year/Web Interfaces for Data Management/Grupo-08-Projeto-Final-IWGD/reddit/reddit/subreddit/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.utils import timezone
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse
import requests
from django.views.decorators.http import require_POST
from .models import *
from django.contrib import messages
import json
from django.db.models import F
from .models import Comment
from .models import Comment
from .forms import *
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import os
from django.core.files.storage import default_storage
from django.conf import settings
import re
import openai
from django.db.models import Max
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from .models import RedditUser, Message
from allauth.socialaccount.models import SocialAccount
import requests
from io import BytesIO
from django.core.files import File


# Create your views here.

openai_api_key = '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'
openai.api_key = openai_api_key

def index(request):

    subreddits = Subreddit.objects.all()

    category_filter = request.GET.get('category_filter')

    if category_filter:
        subreddits = subreddits.filter(Q(category__id=category_filter))

    interest_categories = InterestCategory.objects.all()

    subreddit_search_query = request.GET.get('subreddit_search', '')
    user_search_query = request.GET.get('user_search', '')
    users = []
    following_users = []


    if request.user.is_authenticated:

        if not hasattr(request.user, 'reddituser'):
            country = "PT"
            email = request.user.email
            username = email.split('@')[0]


            google_social_account = SocialAccount.objects.filter(user=request.user, provider='google').first()
            profile_picture = google_social_account.get_avatar_url() if google_social_account else 'default.jpeg'
            if profile_picture != 'default.jpeg':
                response = requests.get(profile_picture)
                if response.status_code == 200:
                    image_content = BytesIO(response.content)
                    image_file = File(image_content)

                    fs = FileSystemStorage()
                    profile_picture = fs.save('profile_image.jpeg', image_file)
            reddit_user = RedditUser(user=request.user, country=country,
                                     profile_picture=profile_picture)
            reddit_user.save()

            if not request.user.is_superuser:
                request.user.username = username
                request.user.save()

        following_users = request.user.reddituser.following.all()


    if subreddit_search_query:
        subreddits = subreddits.filter(Q(name__icontains=subreddit_search_query) | Q(description__icontains=subreddit_search_query))
    if user_search_query:
        users = User.objects.filter(Q(username__icontains=user_search_query))
    subreddits_per_page = int(request.GET.get('subreddits_per_page', 10))
    paginator = Paginator(subreddits, subreddits_per_page)
    page_number = request.GET.get('page')

    try:
        subreddits = paginator.page(page_number)
    except PageNotAnInteger:
        subreddits = paginator.page(1)
    except EmptyPage:
        subreddits = paginator.page(paginator.num_pages)
    return render(request, 'subreddit/index.html', {
        'subreddits': subreddits,
        'subreddits_per_page': subreddits_per_page,
        'user_search_query': user_search_query,
        'users': users,
        'following_users': following_users,
        'interest_categories': interest_categories,
        'selected_category_id': int(category_filter) if category_filter else None,
    })


def registo(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        gender = request.POST['gender']
        country = request.POST['country']
        selected_interests = request.POST.getlist('interests')

        if User.objects.filter(username=username).exists():
            return render(request, 'subreddit/registo.html', {
                'error_message': 'O nome de utilizador já está a ser utilizado.'
            })

        profile_picture = request.FILES.get('profile_picture')
        if profile_picture:

            fs = FileSystemStorage()
            profile_picture = fs.save(f"profile_{username}_{profile_picture.name}", profile_picture)
        else:

            profile_picture = 'default.jpeg'

        user = User.objects.create_user(username, email, password)
        reddit_user = RedditUser(user=user, country=country, gender=gender, profile_picture=profile_picture)
        reddit_user.save()

        for interest_name in selected_interests:
            interest, created = InterestCategory.objects.get_or_create(name=interest_name)
            reddit_user.interests.add(interest)

        messages.success(request, 'Registro bem-sucedido! Faça login para continuar.')
        return redirect('subreddit:login')
    else:
        return render(request, 'subreddit/registo.html')




def login_view(request):
    if request.method == 'POST':
        recaptcha_response = request.POST.get('g-recaptcha-response')
        if recaptcha_response:
            captcha_data = {
                'secret': '6Lf5eYooAAAAALU7LfNVg7Hhm3Jr2lQ_W9Tk3c-F',
                'response': recaptcha_response
            }
            response = requests.post('https://www.google.com/recaptcha/api/siteverify', data=captcha_data)
            result = response.json()
            if result['success']:
                username = request.POST['username']
                password = request.POST['password']
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect(reverse('subreddit:index'))
                else:
                    error_message = 'Dados introduzidos incorretos. Tente novamente.'
                    return render(request, 'subreddit/login.html', {'error_message': error_message})
            else:
                error_message = 'Captcha inválido. Por favor, tente novamente.'
                return render(request, 'subreddit/login.html', {'error_message': error_message})
        else:
            error_message = 'Por favor, prove que não é um robô.'
            return render(request, 'subreddit/login.html', {'error_message': error_message})
    else:
        return render(request, 'subreddit/login.html')


def detalhe_subreddit(request, subreddit_id):
    subreddit = get_object_or_404(Subreddit, pk=subreddit_id)
    posts = Post.objects.filter(subreddit=subreddit)
    posts_per_page = int(request.GET.get('posts_per_page', 10))
    sort_by = request.GET.get('sort_by', 'recent')
    if sort_by == 'recent':
        posts = posts.order_by('-pub_data')
    elif sort_by == 'popular':
        posts = posts.order_by('-likes')
    post_search = request.GET.get('post_search', '')
    if post_search:
        posts = posts.filter(Q(title__icontains=post_search) | Q(content__icontains=post_search))
    paginator = Paginator(posts, posts_per_page)
    page_number = request.GET.get('page')
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'subreddit/detalhe_subreddit.html', {'subreddit': subreddit, 'posts': posts,})


@login_required(login_url="subreddit:login")
def criar_subreddit(request):
    interest_categories = InterestCategory.objects.all()
    formatted_categories = [(category.id, category.get_category_display()) for category in interest_categories]

    if request.method == "POST":
        name = request.POST['name']
        description = request.POST['description']
        creator = request.user
        category_id = request.POST.get('category')
        if category_id:
            category = InterestCategory.objects.get(id=category_id)
        else:
            category = None

        new_subreddit = Subreddit(name=name, description=description, creator=creator, category=category)
        new_subreddit.save()
        return redirect('subreddit:index')

    return render(request, 'subreddit/criar_subreddit.html', {'interest_categories': formatted_categories})




@login_required(login_url="subreddit:login")
def apagar_subreddit(request, subreddit_id):
    subreddit = get_object_or_404(Subreddit, pk=subreddit_id)
    if request.user.is_superuser or request.user.id == subreddit.creator.id:
        subreddit.delete()
    return redirect('subreddit:index')


@login_required(login_url="subreddit:login")
def criar_post(request, subreddit_id):
    subreddit = get_object_or_404(Subreddit, pk=subreddit_id)
    if request.method == "POST":
        title = request.POST['title']
        content = request.POST['content']

        if 'image' in request.FILES:
            image = request.FILES['image']

            fs = FileSystemStorage()


            username = request.user.username
            post_image_name = f"post_{username}_{title}_{image.name}"


            image = fs.save(post_image_name, image)
        else:
            image = None

        novo_post = Post(title=title, content=content, subreddit=subreddit, author=request.user,
                         pub_data=timezone.now(), image=image)
        novo_post.save()
        return redirect('subreddit:detalhe_subreddit', subreddit_id=subreddit_id)

3rd year/Web Interfaces for Data Management/Grupo-08-Projeto-Final-IWGD/reddit/reddit/subreddit/templates/subreddit/detalhe_post.html
{% extends 'subreddit/index.html' %}
{% load static %}
{% block page-title %} {{post.name}} {% endblock %}
{% block content %}
    <div class="container-detalhe">
        <nav class="navbar-detalhe-post">
            <a href="{% url 'subreddit:detalhe_subreddit' subreddit_id=subreddit.id %}" class="nav-link-detalhe-post">Voltar</a>
        </nav>
        <br>

        <div class="post-detalhe-post">
            <h2 class="post-title-detalhe-post">{{ post.title }}</h2><br>
            {% if post.image %}
              <img src="{{ post.image.url }}" alt="Imagem do Post" class="img-post">
            {% endif %}
            <p class="post-content-detalhe-post">{{ post.content }}</p>

            <br><br>
            <a href="javascript:void(0);" class="btn-comment-reddit-detalhe" onclick="toggleCommentBox(this)">Comentar</a>
            <div class="comment-box-detalhe">
                <form action="{% url 'subreddit:criar_comentario' subreddit_id=post.subreddit.id post_id=post.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <br>
                    <textarea name="content" id="content" rows="3" placeholder="Escreva o seu comentário..." required></textarea>
                    <br>
                    <label for="image">Imagem:</label>
                    <input type="file" name="image" accept="image/*">
                    <button type="submit" class="btn-comment-reddit">Enviar Comentário</button>
                </form>
            </div>
            <div class="vote-buttons-detalhe-post">
                        <form method="POST" action="{% url 'subreddit:vote_post' subreddit_id=post.subreddit.id post_id=post.id %}">
                            {% csrf_token %}
                            <button type="submit" name="vote_type" value="like" class="vote-button-detalhe like-button-detalhe" onclick="this.classList.add('jump-animation'); setTimeout(() => this.classList.remove('jump-animation'), 500)">
                                <img src="{% static 'subreddit/img/like.png' %}" alt="Like">
                            </button>
                            <span class="Nlikes-detalhe">{{ post.likes }}</span>
                            <span class="span-black">|</span> <!-- Barra vertical para separar os ícones -->
                            <button type="submit" name="vote_type" value="dislike" class="vote-button-detalhe dislike-button-detalhe" onclick="this.classList.add('sad-animation'); setTimeout(() => this.classList.remove('sad-animation'), 500)">
                                <img src="{% static 'subreddit/img/dislike.png' %}" alt="Dislike">
                            </button>
                            <span class="Ndislikes-detalhe">{{ post.dislikes }}</span>
                        </form>
                        <div class="post-meta-detalhe">
                            <span class="text-muted-detalhe-subreddit">Autor: </span><span class="author-detalhe-subreddit"><a href="{% url 'subreddit:perfil' username=post.author.username %}" class="link-discreto-detalhe-subreddit">{{ post.author }}</a></span>
                            {% if post.author.reddituser.profile_picture %}
                                    <img src="{{ post.author.reddituser.profile_picture.url }}" alt="Foto do utilizador" class ="foto-user-detalhe">
                            {% endif %}
                            <br>
                            <span class="timestamp-detalhe-subreddit">Publicado em: {{ post.pub_data|date:"d/m/Y H:i:s" }}</span>
                        </div>
            </div>
            {% if request.user.is_authenticated and post.author == request.user %}
                <form method="POST" action="{% url 'subreddit:edit_post' subreddit_id=post.subreddit.id post_id=post.id %}">
                    {% csrf_token %}
                    <button type="submit" class="edit-post-button-detalhe-post">Editar Post</button>
                </form>
            {% endif %}
        </div>

        <div class="comments-detalhe-post">
            <h3 class="comments-title-detalhe-post">Comentários</h3>

            <form method="get" action="{% url 'subreddit:filtrar_comentario' subreddit_id=subreddit.id post_id=post.id %}">
                {% csrf_token %}
                <label for="sort_by">Ordenar por:</label>
                <select id="sort_by" name="sort_by">
                    <option value="recent">Mais recentes</option>
                    <option value="popular">Mais populares</option>
                </select>
                <button id="ordenar-button" type="submit">Ordenar</button>
            </form>

            {% for comment in comments %}
            <div class="comment-detalhe-post" id="comment-{{ comment.id }}">

                 <li class="comment-detalhe-post {% if comment.author.username == 'Chat GPT' %}gpt-comment-detalhe-post{% endif %}">
                     <p class="comment-content-detalhe-post">{{ comment.content }}</p>
                     {% if comment.image %}
                        <img src="{{ comment.image.url }}" alt="Imagem do Post" class="img-comment">
                     {% endif %}
                     <div class="post-meta-detalhe">
                         {% if post.author.reddituser.profile_picture %}
                            <img src="{{ comment.author.reddituser.profile_picture.url }}" alt="Foto do utilizador" class ="foto-user-detalhe">
                         {% endif %}
                        <span class="author-detalhe-post">Autor:</span><a href="{% url 'subreddit:perfil' username=comment.author.username %}" class="link-discreto-detalhe-subreddit">{{ comment.author }}</a><br>

                        <span class="timestamp-detalhe-post">Publicado em: {{ comment.pub_data_comentario|date:"d/m/Y H:i:s" }}</span>
                    </div>
                </li>
                <div class="vote-buttons-detalhe-post">
                        <form method="POST" action="{% url 'subreddit:vote_comment' subreddit_id=post.subreddit.id post_id=post.id comment_id=comment.id %}">
                            {% csrf_token %}
                            <button type="submit" name="vote_type" value="like" class="vote-button-detalhe like-button-detalhe" onclick="this.classList.add('jump-animation'); setTimeout(() => this.classList.remove('jump-animation'), 500)">
                                <img src="{% static 'subreddit/img/like.png' %}" alt="Like">
                            </button>
                            <span class="Nlikes-detalhe">{{ comment.likes }}</span>
                            <span class="span-black">|</span> <!-- Barra vertical para separar os ícones -->
                            <button type="submit" name="vote_type" value="dislike" class="vote-button-detalhe dislike-button-detalhe" onclick="this.classList.add('sad-animation'); setTimeout(() => this.classList.remove('sad-animation'), 500)">
                               <img src="{% static 'subreddit/img/dislike.png' %}" alt="Dislike">
                            </button>
                            <span class="Ndislikes-detalhe">{{ comment.dislikes }}</span>
                        </form>
                </div>

                {% if request.user.is_superuser or request.user.id == comment.author.id %}
                <form method="POST" action="{% url 'subreddit:delete_comment' subreddit_id=post.subreddit.id post_id=post.id comment_id=comment.id %}">
                    {% csrf_token %}
                    <button type="submit" class="delete-comment-button-detalhe-post">Apagar</button>
                </form>
                {% endif %}
                {% if request.user.is_authenticated and comment.author == request.user %}
                    <form method="POST" action="{% url 'subreddit:edit_comment' subreddit_id=post.subreddit.id post_id=post.id comment_id=comment.id %}">
                        {% csrf_token %}
                        <button type="submit" class="edit-comment-button-detalhe-post">Editar Comentário</button>
                    </form>
                {% endif %}
            </div>
            {% endfor %}


            {% if comments|length == 0 %}
            <p class="no-comments-detalhe-post">Ainda não há comentários para este post.</p>
            {% endif %}
            <div class="pagination">
                <span class="step-links">
                    {% if comments.has_previous %}
                        <a href="?page=1">&laquo; primeira</a>
                        <a href="?page={{ comments.previous_page_number }}">anterior</a>
                    {% endif %}

                    <span class="current-page">
                        Página {{ comments.number }} de {{ comments.paginator.num_pages }}
                    </span>

                    {% if comments.has_next %}
                        <a href="?page={{ comments.next_page_number }}">seguinte</a>
                        <a href="?page={{ comments.paginator.num_pages }}">última &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>

    <script src="{% static 'subreddit/js/comment_button.js' %}"></script>
{% endblock %}

3rd year/Web Interfaces for Data Management/Grupo-08-Projeto-Final-IWGD/reddit/reddit/subreddit/templates/subreddit/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="x-icon" href="{% static 'subreddit/img/serit_logo.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subreddits</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'subreddit/css/base_styles.css' %}">
    <link rel="stylesheet" href="{% static 'subreddit/css/chat_styles.css' %}">
</head>

<body>
    <header>
        <div class="header-container-index">
            <div class="site-logo">
                <img src="{% static 'subreddit/img/serit_logo.png' %}" alt="Símbolo do Site" class="site-symbol">
                <a  class="serit-inc" href="{% url 'subreddit:index' %}"><h1> Serit.Inc </h1></a>
                <a href="{% url 'subreddit:about_me' %}" class="about-index">Sobre o site</a>
            </div>
            <div class="user-info-index">
                {% if user.is_authenticated %}
                <div class="user-actions-index">
                    <div class="icon-index">
                        <i class="fas-index fa-circle-index"></i>
                    </div>
                    <p class="user-greeting-index">Bem-vindo, <strong>{{ user.username }}</strong>!</p>
                    <div class="user-avatar-index small-avatar-index">
                        <img src="{{ user.reddituser.profile_picture.url }}" alt="{{ user.username }}">
                    </div>
                </div>
                <div class="perout-index">
                    <a href="{% url 'subreddit:perfil' %}" class="perfil-index">Perfil</a>
                    <a href="{% url 'subreddit:lista_chats_privados' %}" class="list-chats-link-index">Meus Chats</a>
                    <a href="{% url 'subreddit:logout' %}" class="logout-index">Logout</a>
                </div>
                {% else %}
                <div class="reglog-index">
                    <a href="{% url 'subreddit:login' %}" class="link-discreto-index">Login</a>
                    <span> | </span>
                    <a href="{% url 'subreddit:registo' %}" class="link-discreto-index">Registar</a>
                </div>
                {% endif %}
            </div>
        </div>
    </header>

    {% block content %}
    <div class="subreddit-list-index">
        <div class="filter-by-category">
            <form method="get" action="{% url 'subreddit:index' %}">
                <select name="category_filter" id="category_filter" class="filter-select">
                    <option value="">Todas as Categorias</option>
                    {% for category in interest_categories %}
                        <option value="{{ category.id }}" {% if category.id == selected_category_id %}selected{% endif %}>{{ category.get_category_display }}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="filter-button">Filtrar</button>
            </form>
        </div>

        <div class="search-container-index">
            <div class="search-bar-index">
                <form method="get" action="{% url 'subreddit:index' %}">
                    <input type="text" name="subreddit_search" placeholder="Pesquisar subreddits">
                    <button type="submit">Pesquisar</button>
                </form>
            </div>
            <div class="user-search-bar-index">
                <form method="get" action="{% url 'subreddit:index' %}">
                    <input type="text" name="user_search" placeholder="Pesquisar users">
                    <button type="submit">Pesquisar Users</button>
                </form>
                {% if users %}
                <ul class="users-index">
                    {% for user in users %}
                    <li>
                        <a href="{% url 'subreddit:perfil' username=user.username %}">{{ user.username }}</a>
                        {% if request.user.is_authenticated and user != request.user and user not in following_users %}
                            <a href="{% url 'subreddit:seguir_amigo' friend_username=user.username %}" class="follow-button-index">Seguir</a>
                        {% elif request.user.is_authenticated and user != request.user and user in following_users %}
                            <a href="{% url 'subreddit:unfollow_amigo' friend_username=user.username %}" class="unfollow-button-index">Deixar de Seguir</a>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>



        {% if subreddits %}
        {% for subreddit in subreddits %}
            <div class="subreddit-index">
                <a href="{% url 'subreddit:detalhe_subreddit' subreddit_id=subreddit.id %}" class="link-discreto-index">
                    <h2>{{ subreddit.name }}</h2>
                    <p>
                        Criador: <a href="{% url 'subreddit:perfil' username=subreddit.creator %}" class="link-discreto-detalhe-subreddit">{{ subreddit.creator }}</a>
                        {% if subreddit.creator.reddituser.profile_picture %}
                        <img src="{{ subreddit.creator.reddituser.profile_picture.url }}" alt="Foto do utilizador" class ="foto-user-detalhe">
                    {% endif %}
                    </p>
                    <p>Categoria: {% if subreddit.category %}{{ subreddit.category.get_category_display }}{% else %}Não possui{% endif %}</p>
                    <p>{{ subreddit.description }}</p>
                </a>
                {% if user == subreddit.creator or user.is_superuser %}
                <form method="POST" action="{% url 'subreddit:apagar_subreddit' subreddit_id=subreddit.id %}">
                    {% csrf_token %}
                    <br><a href="{% url 'subreddit:apagar_subreddit' subreddit_id=subreddit.id %}" class="delete-subreddit-button-index">Apagar Subreddit</a><br><br>
                </form>
                {% endif %}
            </div>
        {% endfor %}
        {% if request.GET.subreddit_search %}
            <a href="{% url 'subreddit:index' %}" class="back-home-index">Voltar à página inicial</a><br><br>
        {% endif %}
        {% if user.is_authenticated %}
            <br><a href="{% url 'subreddit:criar_subreddit' %}" class="create-subreddit-button-index">Criar Subreddit</a><br><br>
        {% endif %}
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if subreddits.has_previous %}
                    <a href="?page=1&subreddit_search={{ search_query }}">&laquo; primeira</a>
                    <a href="?page={{ subreddits.previous_page_number }}&subreddit_search={{ search_query }}">anterior</a>
                {% endif %}

                <span class="current-page">
                    Página {{ subreddits.number }} de {{ subreddits.paginator.num_pages }}
                </span>

                {% if subreddits.has_next %}
                    <a href="?page={{ subreddits.next_page_number }}&subreddit_search={{ search_query }}">seguinte</a>
                    <a href="?page={{ subreddits.paginator.num_pages }}&subreddit_search={{ search_query }}">última &raquo;</a>
                {% endif %}
            </span>
        </div>
        {% else %}
            <p id="no_subreddits" >Ainda não existem subreddits registados!</p>
        {% endif %}

    </div>
{% endblock %}
    <br>

    <footer>
        <div class="copyright-bar">
            <p>&copy; 2023 Serit.Inc. O site mais sério da história. Todos os direitos reservados.</p>
        </div>
    </footer>
</body>
</html>